const TPLS=[{id:"classic",name:"الأصلي"},{id:"masry",name:"خشبي"},{id:"night",name:"ليلي"},{id:"farm",name:"مزرعة"},{id:"souq",name:"شعبي"},{id:"minimal",name:"مينيمال"}];
const HEADER_SVG={};
const PRICE_TPLS=[{id:"cards",name:"كروت الأسعار"},{id:"menu",name:"قائمة سوبرماركت"},{id:"tags",name:"ملصقات كبيرة"},{id:"table",name:"جدول أسعار"}];
const DEFAULT_POS={date:{x:24,y:28},mega:{x:210,y:18},basket:{x:200,y:24},hang:{x:28,y:150},circle:{x:30,y:120},sign:{x:260,y:70}};
const VEG=[{name:"البطاطس",min:"15",max:"20",emoji:"🥔"},{name:"الطماطم",min:"10",max:"15",emoji:"🍅"},{name:"الجزر",min:"10",max:"",emoji:"🥕"},{name:"الباذنجان الحشو",min:"10",max:"",emoji:"🥒"},{name:"الباذنجان الأسود",min:"10",max:"",emoji:"🍆"},{name:"الفلفل",min:"10",max:"15",emoji:"🫑"},{name:"الخيار",min:"10",max:"15",emoji:"🥒"},{name:"الكوسة",min:"20",max:"",emoji:"🥬"},{name:"الليمون",min:"15",max:"40",emoji:"🍋"},{name:"البطاطا (طين)",min:"15",max:"",emoji:"🍠"},{name:"بطاطا تصدير",min:"15",max:"",emoji:"🥔"}];
const FRUIT=[{name:"الفراخ",min:"68",max:"70",emoji:"🐔"},{name:"الموز",min:"35",max:"",emoji:"🍌"},{name:"العنب",min:"35",max:"45",emoji:"🍇"},{name:"المانجو",min:"40",max:"50",emoji:"🥭"},{name:"التين الشوكي",min:"5",max:"",emoji:"🌵"},{name:"التين",min:"40",max:"",emoji:"🟤"}];
function clone(o){return JSON.parse(JSON.stringify(o))}
const DEFAULTS=()=>({template:"classic",priceLayout:"cards",titleSouq:"سوق",titleName:"الرابعة",ribbon:"لمتابعين صفحة بورصة السادات",footerText:"بورصة السادات — متوسط أسعار سوق الرابعة · للتحديث اليومي تابع الصفحة",dateText:"اليوم",circleText:"أكبر صفحة لأسعار السوق في مدينة السادات",hangText:"متابعة يومية لأفضل الأسعار والعروض",pos:clone(DEFAULT_POS),sections:[{title:"أسعار الخضروات",color:"green",items:clone(VEG)},{title:"أسعار الفواكه واللحوم",color:"purple",items:clone(FRUIT)}]});
let state=DEFAULTS(),history=[];
const LS="souq-rabaa-v7";
function snap(){history.push(JSON.stringify(state));if(history.length>30)history.shift()}
function undo(){if(!history.length)return setStatus("لا يوجد تراجع");state=JSON.parse(history.pop());bind();render();setStatus("تم التراجع")}
function applyTplImages(){const I=window.TPL_IMGS||{};const rules=[];["masry","night","farm","souq","minimal"].forEach(k=>{if(I[k])rules.push('.tpl-'+k+' .header{background-image:url("'+I[k]+'")!important;background-size:cover;background-position:center}')});if(!rules.length)return;const s=document.createElement("style");s.textContent=rules.join("\n");document.head.appendChild(s)}
function load(){applyTplImages();try{const r=localStorage.getItem(LS);if(r)state=Object.assign(DEFAULTS(),JSON.parse(r));if(!state.sections&&state.veg){state.sections=[{title:"أسعار الخضروات",color:"green",items:state.veg},{title:"أسعار الفواكه واللحوم",color:"purple",items:state.fruit}]}}catch(e){}bind();render()}
function saveData(){collect();localStorage.setItem(LS,JSON.stringify(state));setStatus("تم الحفظ")}
function resetData(){if(!confirm("الرجوع للقالب الأصلي؟"))return;snap();localStorage.removeItem(LS);state=DEFAULTS();bind();render();setStatus("تم الرجوع للأصل")}
function setStatus(t){const el=document.getElementById("status");el.textContent=t;setTimeout(()=>{if(el.textContent===t)el.textContent=""},2000)}
function bind(){["titleSouq","titleName","ribbon","footerText","dateText","circleText","hangText"].forEach(k=>{const el=document.getElementById(k);el.value=state[k]||"";el.oninput=()=>{collect();renderFlyer()}});
const ht={classic:"#c48a4a",masry:"#8d6e63",night:"#0d1b2a",farm:"#2e7d32",souq:"#bf360c",minimal:"#ddd"};
const pt={cards:"#ffecb3",menu:"#e8f5e9",tags:"#ffeb3b",table:"#eee"};
const I=window.TPL_IMGS||{};
document.getElementById("tpls").innerHTML=TPLS.map(t=>{const src=I[t.id];return `<div class="tpl ${state.template===t.id?"on":""}" onclick="chooseTpl('${t.id}')">${src?`<img src="${src}" alt="${t.name}">`:`<div class="thumb" style="background:${ht[t.id]}">${t.name}</div>`}<span>${t.name}</span></div>`}).join("");
document.getElementById("priceTpls").innerHTML=PRICE_TPLS.map(t=>{const key=t.id==="cards"?"prices-cards":t.id==="menu"?"prices-menu":t.id==="tags"?"prices-tags":"";const src=key&&I[key];return `<div class="tpl ${state.priceLayout===t.id?"on":""}" onclick="choosePriceTpl('${t.id}')">${src?`<img src="${src}" alt="${t.name}">`:`<div class="thumb" style="background:${pt[t.id]}">${t.name}</div>`}<span>${t.name}</span></div>`}).join("")}
function chooseTpl(id){snap();state.template=id;bind();renderFlyer()}
function choosePriceTpl(id){snap();state.priceLayout=id;bind();renderFlyer()}
function collect(){["titleSouq","titleName","ribbon","footerText","dateText","circleText","hangText"].forEach(k=>state[k]=document.getElementById(k).value);
(state.sections||[]).forEach((sec,si)=>{const t=document.getElementById("s-t-"+si);if(t)sec.title=t.value;(sec.items||[]).forEach((p,i)=>{const n=document.getElementById(`s-${si}-n-${i}`);if(!n)return;p.name=n.value;p.min=document.getElementById(`s-${si}-min-${i}`).value;p.max=document.getElementById(`s-${si}-max-${i}`).value})})}
function editors(){document.getElementById("sectionsEditor").innerHTML=(state.sections||[]).map((sec,si)=>`<div class="sec-box"><div class="sec-head"><input id="s-t-${si}" value="${sec.title||""}"/><button class="btn-d mini" onclick="removeSection(${si})">حذف القسم</button></div>${(sec.items||[]).map((p,i)=>`<div class="row3"><input id="s-${si}-n-${i}" value="${p.name||""}"/><input id="s-${si}-min-${i}" value="${p.min||""}"/><input id="s-${si}-max-${i}" value="${p.max||""}"/></div><div class="btns"><button class="btn-d mini" onclick="removeItem(${si},${i})">حذف الصنف</button></div>`).join("")}<button class="btn-ok mini" onclick="addItem(${si})">إضافة صنف</button></div>`).join("");
document.querySelectorAll(".editor input").forEach(inp=>{if(["titleSouq","titleName","ribbon","footerText","dateText","circleText","hangText"].includes(inp.id))return;inp.addEventListener("input",()=>{collect();renderFlyer()})})}
function addSection(){snap();collect();state.sections.push({title:"قسم جديد",color:"green",items:[{name:"صنف جديد",min:"10",max:"",emoji:"🛒"}]});render();setStatus("تمت إضافة قسم")}
function removeSection(si){snap();collect();state.sections.splice(si,1);render();setStatus("تم حذف القسم")}
function addItem(si){snap();collect();state.sections[si].items.push({name:"صنف جديد",min:"10",max:"",emoji:"🛒"});render();setStatus("تمت إضافة صنف")}
function removeItem(si,i){snap();collect();state.sections[si].items.splice(i,1);render();setStatus("تم حذف الصنف")}
function productImg(p){const src=(window.PRODUCT_IMGS||{})[p.name];if(src)return `<img src="${src}" alt="${p.name}">`;return `<span>${p.emoji||"🛒"}</span>`}
function priceHTML(p){if(p.max&&p.max!==p.min)return `<span class="from">من</span><span class="num">${p.min}</span><span class="to">إلى ${p.max}</span><span class="unit">جنيه</span>`;return `<span class="num">${p.min}</span><span class="unit">جنيه</span>`}
function card(p){return `<article class="card"><h3>${p.name}</h3><div class="pic">${productImg(p)}</div><div class="price">${priceHTML(p)}</div></article>`}
function rangeText(p){return(p.max&&p.max!==p.min)?`${p.min}–${p.max}`:(p.min||"—")}
function menuRow(p){return `<div class="menu-row"><div class="emo">${productImg(p)}</div><div class="nm">${p.name}</div><div class="pr">${rangeText(p)}<small>جنيه / كيلو</small></div></div>`}
function tagCard(p){return `<div class="tag-card"><h3>${p.name}</h3><span class="emo">${productImg(p)}</span><div class="tag-price-wrap"><div class="tag-price">${rangeText(p)}<small>جنيه / كيلو</small></div></div></div>`}
function tableBlock(list,cls){return `<table class="layout-table ${cls||""}"><thead><tr><th>الصنف</th><th>السعر</th></tr></thead><tbody>${list.map(p=>`<tr><td>${productImg(p)} ${p.name}</td><td class="pr">${rangeText(p)} جنيه</td></tr>`).join("")}</tbody></table>`}
function pricesHTML(list,three){const L=state.priceLayout||"cards";if(L==="menu")return `<div class="plist layout-menu">${list.map(menuRow).join("")}</div>`;if(L==="tags")return `<div class="plist layout-tags">${list.map(tagCard).join("")}</div>`;if(L==="table")return tableBlock(list,three?"fruit":"");return `<div class="grid ${three?"three":""}">${list.map(card).join("")}</div>`}
function headerPhotoHTML(){if(state.template==="classic")return"";const I=window.TPL_IMGS||{};const src=I[state.template];return src?`<img class="header-photo" src="${src}" alt="${state.template}">`:""}
function headerSignHTML(){const t=state.template;const inner=`<div class="souq-word">${state.titleSouq}</div><div class="rabaa-word">${state.titleName}</div>`;if(t==="night")return `<div class="drag sign-night" data-k="sign" style="${posStyle("sign")}">${inner}</div>`;if(t==="farm")return `<div class="drag sign-farm" data-k="sign" style="${posStyle("sign")}">${inner}</div>`;if(t==="souq")return `<div class="drag sign-souq" data-k="sign" style="${posStyle("sign")}">${inner}</div>`;if(t==="minimal")return `<div class="drag sign-minimal" data-k="sign" style="${posStyle("sign")}">${inner}</div>`;return `<div class="drag wood-sign" data-k="sign" style="${posStyle("sign")}"><div class="wood-plank">${inner}</div></div>`}
function posStyle(k){const p=state.pos[k]||DEFAULT_POS[k];const fromRight=(k==="date"||k==="mega"||k==="hang");return fromRight?`right:${p.x}px;top:${p.y}px`:`left:${p.x}px;top:${p.y}px`}
function renderFlyer(){const f=document.getElementById("flyer");f.className="tpl-"+state.template;f.innerHTML=`<div class="header" id="headerZone">${headerPhotoHTML()}<div class="drag mega" data-k="mega" style="${posStyle("mega")}">📣</div><div class="drag badge-today" data-k="date" style="${posStyle("date")}">${state.dateText}</div><div class="drag basket" data-k="basket" style="${posStyle("basket")}">🫺🥗</div><div class="drag hang-left" data-k="hang" style="${posStyle("hang")}">${state.hangText}</div><div class="drag circle-right" data-k="circle" style="${posStyle("circle")}">${state.circleText}</div>${headerSignHTML()}</div><div class="red-ribbon">${state.ribbon}</div>${(state.sections||[]).map((sec,i)=>`<div class="bar ${sec.color==="purple"?"purple":"green"}">${sec.title||""}</div>${pricesHTML(sec.items||[],i>0&&(sec.items||[]).length<=6)}`).join("")}<div class="footer">${state.footerText||""}</div>`;bindDrag()}
function render(){editors();renderFlyer()}
let dragging=null,start=null,didSnap=false;
function bindDrag(){document.querySelectorAll("#headerZone .drag").forEach(el=>el.addEventListener("pointerdown",onDown))}
function onDown(e){const el=e.currentTarget;dragging=el;didSnap=false;el.classList.add("hold");const k=el.dataset.k;const p=state.pos[k];start={px:e.clientX,py:e.clientY,x:p.x,y:p.y,k};el.setPointerCapture(e.pointerId);window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",onUp)}
function onMove(e){if(!dragging||!start)return;if(!didSnap){snap();didSnap=true}const dx=e.clientX-start.px,dy=e.clientY-start.py;const fromRight=(start.k==="date"||start.k==="mega"||start.k==="hang");state.pos[start.k].x=Math.max(0,start.x+(fromRight?-dx:dx));state.pos[start.k].y=Math.max(0,start.y+dy);const p=state.pos[start.k];if(fromRight)dragging.style.right=p.x+"px";else dragging.style.left=p.x+"px";dragging.style.top=p.y+"px"}
function onUp(){if(dragging)dragging.classList.remove("hold");dragging=null;start=null;window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",onUp)}
async function exportImage(){collect();renderFlyer();setStatus("جارٍ تجهيز الصورة...");try{const canvas=await html2canvas(document.getElementById("flyer"),{scale:2,useCORS:true,backgroundColor:"#fff6d9"});const a=document.createElement("a");a.download="souq-rabaa-"+new Date().toISOString().slice(0,10)+".png";a.href=canvas.toDataURL("image/png");a.click();setStatus("تم تنزيل الصورة")}catch(err){console.error(err);setStatus("تعذّر التصدير")}}
load();
